require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdhocTablesController do

  # This should return the minimal set of attributes required to create a valid
  # AdhocTable. As you add validations to AdhocTable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all adhoc_tables as @adhoc_tables" do
      adhoc_table = AdhocTable.create! valid_attributes
      get :index
      assigns(:adhoc_tables).should eq([adhoc_table])
    end
  end

  describe "GET show" do
    it "assigns the requested adhoc_table as @adhoc_table" do
      adhoc_table = AdhocTable.create! valid_attributes
      get :show, :id => adhoc_table.id.to_s
      assigns(:adhoc_table).should eq(adhoc_table)
    end
  end

  describe "GET new" do
    it "assigns a new adhoc_table as @adhoc_table" do
      get :new
      assigns(:adhoc_table).should be_a_new(AdhocTable)
    end
  end

  describe "GET edit" do
    it "assigns the requested adhoc_table as @adhoc_table" do
      adhoc_table = AdhocTable.create! valid_attributes
      get :edit, :id => adhoc_table.id.to_s
      assigns(:adhoc_table).should eq(adhoc_table)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdhocTable" do
        expect {
          post :create, :adhoc_table => valid_attributes
        }.to change(AdhocTable, :count).by(1)
      end

      it "assigns a newly created adhoc_table as @adhoc_table" do
        post :create, :adhoc_table => valid_attributes
        assigns(:adhoc_table).should be_a(AdhocTable)
        assigns(:adhoc_table).should be_persisted
      end

      it "redirects to the created adhoc_table" do
        post :create, :adhoc_table => valid_attributes
        response.should redirect_to(AdhocTable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adhoc_table as @adhoc_table" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdhocTable.any_instance.stub(:save).and_return(false)
        post :create, :adhoc_table => {}
        assigns(:adhoc_table).should be_a_new(AdhocTable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdhocTable.any_instance.stub(:save).and_return(false)
        post :create, :adhoc_table => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adhoc_table" do
        adhoc_table = AdhocTable.create! valid_attributes
        # Assuming there are no other adhoc_tables in the database, this
        # specifies that the AdhocTable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdhocTable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => adhoc_table.id, :adhoc_table => {'these' => 'params'}
      end

      it "assigns the requested adhoc_table as @adhoc_table" do
        adhoc_table = AdhocTable.create! valid_attributes
        put :update, :id => adhoc_table.id, :adhoc_table => valid_attributes
        assigns(:adhoc_table).should eq(adhoc_table)
      end

      it "redirects to the adhoc_table" do
        adhoc_table = AdhocTable.create! valid_attributes
        put :update, :id => adhoc_table.id, :adhoc_table => valid_attributes
        response.should redirect_to(adhoc_table)
      end
    end

    describe "with invalid params" do
      it "assigns the adhoc_table as @adhoc_table" do
        adhoc_table = AdhocTable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdhocTable.any_instance.stub(:save).and_return(false)
        put :update, :id => adhoc_table.id.to_s, :adhoc_table => {}
        assigns(:adhoc_table).should eq(adhoc_table)
      end

      it "re-renders the 'edit' template" do
        adhoc_table = AdhocTable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdhocTable.any_instance.stub(:save).and_return(false)
        put :update, :id => adhoc_table.id.to_s, :adhoc_table => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adhoc_table" do
      adhoc_table = AdhocTable.create! valid_attributes
      expect {
        delete :destroy, :id => adhoc_table.id.to_s
      }.to change(AdhocTable, :count).by(-1)
    end

    it "redirects to the adhoc_tables list" do
      adhoc_table = AdhocTable.create! valid_attributes
      delete :destroy, :id => adhoc_table.id.to_s
      response.should redirect_to(adhoc_tables_url)
    end
  end

end
